# Render configuration file
version: 1

services:
  - type: web
    name: read-it-now
    env: python
    plan: starter
    buildCommand: "./build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --worker-class sync app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/.playwright
      - key: FLASK_ENV
        value: production
    region: oregon
